spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: recipe-service
          uri: lb://recipe-service
          predicates:
            - Path=/api/recipe/**
        - id: ingredient-service
          uri: lb://ingredient-service
          predicates:
            - Path=/api/**
        - id: recipe-search-service
          uri: lb://recipe-search-service
          predicates:
            - Path=/recipe-search/**
      discovery:
        locator:
          enabled: true

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
server:
  port: 8080