version: '3.6'



services:
  elasticsearch:
    image: elasticsearch:7.17.13
    container_name: elasticsearch
#    volumes:
#      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      - node.name=elasticsearch
      - 'ES_JAVA_OPTS: -Xms256m -Xmx256m'
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk-network


  logstash:
    image: logstash:7.17.13
    container_name: logstash
#    volumes:
#      - ./logstash/:/logstash_dir
#    command: logstash -f /logstash_di /logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - '127.0.0.1:9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx256m"
    networks:
      - elk-network


  kibana:
    image: kibana:7.17.13
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk-network

networks:
   elk-network:
      driver: bridge
#volumes:
#  elastic_data: {}

